### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tmmgrafikr** [grafikr/shopify-devserver#12]
I may think there is a minor issue with the refreshing of page.
If it gets to the point of blocking the IP.

I sometimes get this error on `theme watch` cmd:
```request failed after 5 retries with error: Put https://frederikbaggerstore-dk.myshopify.com/admin/api/unstable/themes/121021399176/assets.json: write tcp 192.168.1.151:50366->23.227.38.74:443: write: no buffer space available```

This errors doesn't stop the devserver, but it's like it's starting a loop of some art, my com is going haywire when it happens 😅 
A bit vague error report i know, not sure how to test it either 🤷

**Comment by andershagbard** [comment]
Maybe solved by https://github.com/grafikr/DEUS/issues/152

**Comment by andershagbard** [comment]
This is more of a [themekit issue](https://github.com/Shopify/themekit). Not solving here.
