### ISSUE TITLE
Request loop causes error

### ISSUE THREAD

**Issue by Curzey** [grafikr/shopify-devserver#6]
Seems like there's some proxy error on 404 pages that keeps running and spamming the Shopify servers. Check screenshots. This only happens on `yarn serve`, so gotta be something with the devServer. 

<img width="832" alt="Skærmbillede 2021-11-19 kl  09 34 12" src="https://user-images.githubusercontent.com/23375565/142591294-f59d10ad-e39c-439e-bf95-d0dfa09d2206.png">

<img width="906" alt="Skærmbillede 2021-11-19 kl  09 35 17" src="https://user-images.githubusercontent.com/23375565/142591462-23bc1edb-88b8-403f-8a90-5e4a1bfabbd2.png">

**Comment by andershagbard** [comment]
This is actually intended behavior. But we probably could throttle the requests a bit, by only sending requests 10 seconds after file changes in the `src` folder. 

Right now, we are checking if the requests return a different body, and if they to, we reload the page.

**Comment by Curzey** [comment]
Then I guess it would be better to just develop the /404 page with `yarn watch`. 

...or maybe just do it quicker 😎

**Comment by andershagbard** [comment]
It doesn't seem specific to the 404 page. It sends requests on all page types.

**Comment by andershagbard** [comment]
Solved in v2 by not having live reload _(For now)_
